name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install firebases
        run: npm install -g firebase-tools   

      - name: Install dependencies
        run: yarn && cd functions && yarn

      - name: Deploy to Firebase
        run: firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
       
